### ISSUE TITLE
IPG files are no longer available for copying to other iTunes installs

### ISSUE THREAD

**Issue by thetrueyoshifan** [Olsro/ipodclickwheelgamespreservationproject#10]
The guide refers to accessing the IPG directory within the repo for the files to get rid of the "Transfer Purchases" dialog in iTunes. However, these IPG files have been removed from the repo, and older commits no longer reflect the current state of the dumping project. Is there another source for these IPG files to fix this message?

**Comment by Olsro** [comment]
IPGs are now available there: https://github.com/Olsro/ipodclickwheelgamespreservationproject/releases
I will update the documentation, thank you

**Comment by Olsro** [comment]
Documentation updated
