### ISSUE TITLE
No UTM file to copy

### ISSUE THREAD

**Issue by Kwik117** [Olsro/ipodclickwheelgamespreservationproject#11]
trying to do this on linux, and i have been over the page a bunch of times. there is no .utm file to copy. cant make it work without it. Should probably link it down in the instructions where it says to copy it. then its right there, and you dont have to go looking for it.

**Comment by Olsro** [comment]
Hello

Looks like you've forget to do the step 2: https://github.com/Olsro/ipodclickwheelgamespreservationproject?tab=readme-ov-file#2-download-the-virtual-machine-and-all-of-the-games-files

**Comment by Olsro** [comment]
I improved the documentation a bit to precise that downloading the virtual machine means downloading the utm file
