### ISSUE TITLE
Suggestion: re-add the SHA-256 hashes for the downloads to the repo

### ISSUE THREAD

**Issue by mariomadproductions** [Olsro/ipodclickwheelgamespreservationproject#13]
So that there is still some kind of easily downloadable "source of truth" for the files.

**Comment by Olsro** [comment]
Will do it again starting the next release, thank you

**Comment by mariomadproductions** [comment]
Thanks

**Comment by mariomadproductions** [comment]
@Olsro just to clarify, I meant in the repo itself. Because there isn't really an proper tool for downloading github-specific stuff like release descriptions.

**Comment by Olsro** [comment]
OK

**Comment by Olsro** [comment]
https://github.com/Olsro/ipodclickwheelgamespreservationproject/blob/main/HASHS.md

**Comment by mariomadproductions** [comment]
Thanks
