### ISSUE TITLE
Expired password on windows

### ISSUE THREAD

**Issue by Glujaz** [Olsro/ipodclickwheelgamespreservationproject#16]
When running the VM, windows starts, and says the password has to be changed. Original password is required, but not given in any FAQ or other documentation in this git.

**Comment by Glujaz** [comment]
Solution : the password is empty. Just type nothing in the fiels, and confirm new password.

**Comment by Olsro** [comment]
Hello, this is a bug caused by an expiring password policy. This will be fixed in the next version, when I will be able to preserve more games.
