### ISSUE TITLE
Password for virtual machine expired in VMware

### ISSUE THREAD

**Issue by NotHardEngineer** [Olsro/ipodclickwheelgamespreservationproject#18]
![image](https://github.com/user-attachments/assets/57b91099-35ed-46d8-814e-9d08c36ff6c8)
![image](https://github.com/user-attachments/assets/fa8ae03d-0262-4373-8922-d76b4df1629b)
I tried a couple obvious variants for "old password" please add machine password to readme

**Comment by NotHardEngineer** [comment]
I managed to get in via changing time on host system to 9 nov 2024

**Comment by NotHardEngineer** [comment]
didn't saw already closed issue, sorry.

**Comment by Olsro** [comment]
I thought I would had the opportunity to preserve more games to justify me to release a new virtual machine, but unfortunately, as of today, 3 games are still missing. I was not motivated to do a release just to fix this for the moment, but as you noticed, changing the password yourself or changing the date from your PC fixed this annoying issue
