### ISSUE TITLE
iTunes Says that my computer needs to be authorized

### ISSUE THREAD

**Issue by Alexmoon2207** [Olsro/ipodclickwheelgamespreservationproject#19]
I'm using UTM on and intel iMac, and can't get past this screen. I have tried older versions of the utm file and have restarted the vm multiple times. 
<img width="2560" alt="Screen Shot 2024-12-10 at 10 46 48 PM" src="https://github.com/user-attachments/assets/b8c72461-b4f0-430e-9c1d-1db711825c4d">

**Comment by Olsro** [comment]
Hello, please update the Virtual Machine to the latest version then retry.

**Comment by Alexmoon2207** [comment]
Re-downloading the UTM file fixed the issue. Thanks a ton!
