### ISSUE TITLE
Problems extracting virtual machine files 

### ISSUE THREAD

**Issue by Awlexegrecki** [Olsro/ipodclickwheelgamespreservationproject#2]
I am using Mac OS and I am using the Unarchiver as the instructions detailed. When extracting the files, I usually get an error along the lines of "The file could not be written to" or "The archive is incomplete." The errors vary, but I believe this may have something to do with how they are compressed. Double compressing the utm file through 7z then whatever the .001 is? I believe it would be much easier if there was another platform on which they could be hosted, such as MEGA or Google Drive. However, it is also possible that the issues are on my end, including problems when downloading the file or unarchiver incorrectly seeing the files.

**Comment by Olsro** [comment]
Hello,

- You should open only the first archive file
- All archive files should be in the exact same folder
- Don't do it while the download is still in progress !
- There is 4 parts. Don't forget to download all of them ;)

It will produce the .utm file (you should NOT unpack the .utm file, just import it in UTM directly). Also, the .utm by itself is not a compressed archive but a virtual folder (like an .app for any mac application) so there's no problem in particular about doing this.

**Comment by Olsro** [comment]
Open "iPod Clickwheel Games Preservation Project.utm.7z.001" with "The Unarchiver". I personnally do it with Right Click -> Open With. I directly get the .utm as an Output.

I use "The Unarchiver" version 4.3.8 personnally.

"Don't do what while what what download is in progress?"
-> Do not try to unpack

**Comment by Olsro** [comment]
Also, on workupload, you should not click the button "Download archive" which will always download the first. Just click on each "Download" button rather

**Comment by Awlexegrecki** [comment]
When trying to open it, I received one of the errors I was receiving before: "The archive file is incomplete"

**Comment by Olsro** [comment]
Can you screenshot me please your whole current folder ?

**Comment by Awlexegrecki** [comment]
Should I make a new folder for the archives?

**Comment by Olsro** [comment]
Nope. The only condition is that all the parts must be in the same folder when you attempt to extract it.
Here is a full picture of my folder in the Finder so you can compare if you have thing looking strange on yours.

<img width="697" alt="image" src="https://github.com/user-attachments/assets/1d2e65ae-5ebb-4449-b368-484acc9a47ea">

**Comment by Awlexegrecki** [comment]
![image](https://github.com/user-attachments/assets/545d9d40-0842-4600-900d-cd6f6ad7d46a)

**Comment by Olsro** [comment]
It should not produce any kind of error. Do you have enough memory on your Mac ? It requires around 10GB to extract.

The qcow2 is located inside the .utm folder.

**Comment by Awlexegrecki** [comment]
I feel so stupid 😖
I had less than a megabyte free on my Mac... 
Thank you!

**Comment by Olsro** [comment]
The issue also come by the fact that modern MacOS versions (if I remember right) do not even show the bottom bar by default which indicates free space. Also, The Unarchiver is very misleading and confusing on the error.

Have fun with the 2 games, glad that you've solved your problem and it might help someone else, who knows...
