### ISSUE TITLE
Games do not launch on a flash modded iPod 5.5

### ISSUE THREAD

**Issue by 3urobeat** [Olsro/ipodclickwheelgamespreservationproject#3]
Heya, cool project you've started!

Sadly none of the games in this repository start on my flash modded iPod 5.5 (thick 80GB model with an iFlash Quad and a 512GB Samsung Micro-SD).  
Upon launching any game it displays (roughly translated): "This game cannot be launched. Please connect your iPod to iTunes and install the game again."

They do work without a problem on another 5.5 gen (also thick 80GB model) and a 6th gen (80GB model) though.  
Both are stock with their original HDD.

I don't think there is anything you can do about this, however I just wanted to let you (and anyone else with a flashmodded 'Pod) know. If someone has any idea to solve this, please comment.  
(I obviously already tried to restart the device using MENU+Select and also re-synced the games again) 

Also, PS:  
For anyone on Arch\* systems - to install the packages you need to run: `pacman -S qemu-full remmina`

**Comment by Olsro** [comment]
Hey,

Not sure at all about that, but maybe, the games auth themselves on the iPod using some kind of unique S/N from the hard drive itself. And maybe iFlash devices have no correct identity so the iPod cannot decrypt the game on-the-fly just like it does with a real hard drive.

My iPods are personnally CF modded. I think you should report this to Tarkan which maintains the iFlash adapters: https://www.iflash.xyz/

He claims full support with Stock OS, so it is a bug/issue that should be a concern for him.

I hope that thanks to this VM, we will know more in the future how those games and their DRM works under the hood to be able to fix that kind of edge cases.

Kind regards

**Comment by 3urobeat** [comment]
Thanks for the quick response! 

I've shot them a contact request and I'll update this issue when I get an answer.

**Comment by CatsLover2006** [comment]
I have swapped the hard drives between two of my iPod 5.5G’s before. While the games never worked on the one with the mismatched serial number, the hard drive serial swap caused no problems with launching the games on the correct iPod.

**Comment by 3urobeat** [comment]
Hey, so I've got a response from iFlash. The relevant part:
> If the only thing that stops it working is the iFlash board, then it is possible the DRM used by the games is using some identifier from the original harddrive for the authentication process.
> 
> Sadly if that is the case there is nothing we can do about that as we cannot emulate the original HDD, as the point of our boards is that users can install any storage combination and size they want.
> 
> Have you tried a fresh restore on the iPod using the project virtual machine, to see how that goes. The iPod DRM also uses an GUID created when the iPod is restored.

I'd might have to restore my iPod afterall to try this out. Maybe I have another SD card floating around so that I don't have to re-sync the content on my current SD card.  
I'll update should I find some time this weekend to try it out.

**Comment by 3urobeat** [comment]
Alright, a week later than expected, but I just re-downloaded the last version (8) of the VM, resynced the 5 games available (Asphalt, Bejeweled, Chinese Checkers, Crystal Defenders & Tetris), copied over iPod_Control and they load without any issues now.

Sorry that I couldn't find a fix apart from just resyncing using the latest version, but it works for me now.  
(iTunes isn't listing the other games for me though, not sure if I missed something, so I can't test them)

**Comment by Olsro** [comment]
Please read the documentation about other games. It is very easy, but the process has changed to workaround the 5 Apple ID limit and put all games.
Also, if you like my project, feel free to tip me on Patreon: https://www.patreon.com/Olsro
