### ISSUE TITLE
Version 8: ...7z.003; failed to write to file

### ISSUE THREAD

**Issue by Awlexegrecki** [Olsro/ipodclickwheelgamespreservationproject#6]
When using the Unarchiver to extract version 8, I received the error with the .003 file that it failed to write to the file. I made sure to unarchive the .001 file and I reinstalled the .003 file, and both times it failed. I tried the corrupted .utm file it outputted and, of course, I received an error. The extraction worked for the previous cersions, so I believe it may be a problem with this version?

**Comment by Olsro** [comment]
Hello,

I just downloaded the 3 parts from the latest release on GitHub Releases and I could extract the .utm file just fine using The Unarchiver on my Mac.

I think you don't have enough free space on your hard drive to extract it.
<img width="642" alt="image" src="https://github.com/user-attachments/assets/f96d2f0f-1a35-48f2-961e-c3cca4bb9402">

**Comment by Awlexegrecki** [comment]
so embarrassing... 😖
