### ISSUE TITLE
Help clarifying 5-per-5 each sync

### ISSUE THREAD

**Issue by PeterDaGrape** [Olsro/ipodclickwheelgamespreservationproject#7]
Hello, I tried following instructions but Im stuck at the part on copying from iTunes, as it says copy 5-per-5 each sync, and there are 6 games on the VM, so which ones do I use, and also if I copy all 6 I get the problem with Apple ID limits

**Comment by PeterDaGrape** [comment]
yes that does clarify thanks, I found the solution to get everything running in a reddit comment about ticking everything except Texas holdem to get everything, maybe worth mentioning that on here. Thank you

**Comment by Olsro** [comment]
More games will be added in the future so writing "select everything excepted texas hold'em" will be confusing

Have fun with the games :)
