### ISSUE TITLE
Add note to enable "Enable disk use" for the iPod before connecting to UTM.

### ISSUE THREAD

**Issue by EthanBezz** [Olsro/ipodclickwheelgamespreservationproject#8]
When disk use is not enabled, the iPod will auto-eject after the initial sync on connection. When you try to start a sync in iTunes, it will attempt to reconnect the iPod, but it ends up connecting to the host machine instead, causing UTM to throw an error. With disk use enabled, the iPod doesn't auto-eject, therefore avoiding the reconnection issue.

**Comment by Olsro** [comment]
Thanks to your message, I improved a bit the documentation to make the connection method more clear

**Comment by EthanBezz** [comment]
I did follow those instructions but couldn't get it to work after several attempts, until I enabled disk use, then it was fine. Do your iPods have disk use enabled? I think, at the very least, it should be added as a suggestion for if someone is having issues with attempting to sync their iPod with iTunes in the VM.

**Comment by Olsro** [comment]
Ah, sorry, I was confusing with disk mode.

Disk use is that option to tick on iTunes (but it is ON by default).

Thank you, I will update the documentation accordingly

**Comment by EthanBezz** [comment]
Yep, perfect! Will close it now. Thanks.
