### ISSUE TITLE
Keep getting this every time I try to start :( [Ubuntu 22.04.1]

### ISSUE THREAD

**Issue by Robotic80401** [Olsro/ipodclickwheelgamespreservationproject#9]
WARNING: Closing this terminal window will stop the virtual machine !
qemu-system-x86_64: warning: global PIIX4_PM.disable_s3=1 not used
./start_qemu.sh: line 3: 17035 Killed                  qemu-system-x86_64 -L qemu -spice unix=off,addr=127.0.0.1,port=17474,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,name=org.qemu.monitor.qmp.0,id=org.qemu.monitor.qmp -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device virtio-vga -smp 2 -machine q35,vmport=off,i8042=off,hpet=off -accel kvm -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -drive if=pflash,format=raw,unit=0,file.filename=qemu/edk2-x86_64-code.fd,file.locking=off,readonly=on -drive "if=pflash,unit=1,file=iPod Clickwheel Games Preservation Project.utm/Data/efi_vars.fd" -m 2048 -audiodev spice,id=audio0 -device intel-hda -device hda-duplex,audiodev=audio0 -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device nec-usb-xhci,id=usb-controller-0 -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device ide-hd,bus=ide.0,drive=driveA973B7BF-F17A-44C5-A6D7-B6D819938FDC,bootindex=0 -drive "if=none,media=disk,id=driveA973B7BF-F17A-44C5-A6D7-B6D819938FDC,file.filename=iPod Clickwheel Games Preservation Project.utm/Data/A973B7BF-F17A-44C5-A6D7-B6D819938FDC.qcow2,discard=unmap,detect-zeroes=unmap" -device virtio-serial -device virtserialport,chardev=org.qemu.guest_agent,name=org.qemu.guest_agent.0 -chardev spiceport,name=org.qemu.guest_agent.0,id=org.qemu.guest_agent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -name "iPod Clickwheel Games Preservation Project" -uuid A9FC3197-EE40-4EF9-A948-461B0B194755 -rtc bas

And then it crashes.

**Comment by Olsro** [comment]
How much RAM have your computer ? Maybe you don't have enough. 2GB is necessary (which is pretty low)
Have you tried launching qemu using the slow script ?

**Comment by Robotic80401** [comment]
My computer has 8GB RAM with 7.36GB usable. I tried both the normal script and slow script multiple times, and got the same result. Could it maybe have something to do with my CPU? It's an AMD Ryzen 5 4600H. I did check in the launcher scripts and I didn't see anything about AMD in them, I just saw Intel. Is it maybe because I was booting Ubuntu off a USB instead of installing? Thanks so much for your reply though!

**Comment by Olsro** [comment]
https://superuser.com/questions/1809595/how-to-find-out-exactly-which-process-was-killed-by-oom-killer try to do this to check if the OOM killer from the kernel is responsible for the killed process.

Also, you may try booting Ubuntu 24.04. I had success with Ubuntu 24.04 MATE (installed on a second partition), but I don't know about earlier versions...

**Comment by Robotic80401** [comment]
FORGOT TO REPLY, SORRY!!
Little update though: It seems to have just fixed itself. I tried again yesterday and did nothing differently however it worked this time for some reason. I loaded 2 games onto my iPod. It works like a dream, thank you!

**Comment by Olsro** [comment]
Very happy for you, have fun with the games ! :)

Feel free to tip me if you like my work: https://www.patreon.com/Olsro
